name: continous-build
on: 
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
     - main
  workflow_dispatch:
# Testing our first workflow
env: 
  name: Niran
jobs:
  build: 
    runs-on: ubuntu-latest
    environment: dev
    env:
      lastname: Subramanian
    steps:
      - name: step1
        env:
          greetings: GoodMorning
          name: Joy
        run: |
          echo "$greetings from $name $lastname, job1 of workflow1 running in environment ${{ vars.environment}}"
          echo "Running on server ${{ vars.servername}} with credentials ${{ secrets.SERVER_PASSWD }} and API KEY ${{ secrets.APIKEY }} "
          sleep 10
          hostname
      - name: my step2
        run: |
          echo "$greetings from $name"
          sleep 10
      - run: |
          echo "hello from step3"
          sleep 10
      - name: my step4 for testing multiple lines of code execution
        run: |
          ls -l
          pwd
          sudo cat /etc/os-release
          uname -a
          echo "final step4 execution done"
  feature: 
    runs-on: niran
    environment: feature
    steps:
      - name: step1
        run: |
           echo "Running on server ${{ vars.servername}} with credentials ${{ secrets.SERVER_PASSWD }} and API KEY ${{ secrets.APIKEY }} "
           echo "Running on server ${{ vars.servername}} with credentials ${{ secrets.SERVER_PASSWD }} and API KEY ${{ secrets.APIKEY }} " >> /tmp/actionfile
           echo "Running on server ${{ vars.servername}} "
           sleep 30
           hostname
      - name: my step2
        run: |
          echo "hello from $name"  
          sleep 10
